# Needed credentials.yml. To edit yours:
# VISUAL="vim" bin/rails credentials:edit

secret_key_base: "your-secret-key-base"
google_oauth:
  client_id: "your-client-id"
  client_secret: "your-client-secret"
sentry_dsn: "your-sentry-dsn"
mailjet:
  api_key: "your-api-key"
  secret_key: "your-secret-key"
app:
  host: "your-host"
  mailer_sender: "YourApp <no-reply@your-host>"